version: '3'
services:
  url-shortener-api:
    image: guilhermelopes764/url-shortener-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database
    command: ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/app.ts"]
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: