openapi: 3.0.0
info:
  title: Link Shortener API
  version: 1.0.0
  description: API for shortening URLs and redirecting to the originals.
paths:
  /url:
    post:
      summary: Shorten a URL
      description: Creates a new shortened link from an original URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
      responses:
        '200':
          description: Shortened link created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: Unique identifier of the shortened link.
                  originalURL:
                    type: string
                    format: uri
                    description: Original URL provided by the user.
                  createdAt:
                    type: string
                    format: date-time
                    description: Date and time when the shortened link was created.
                  expiresAt:
                    type: string
                    format: date-time
                    description: Date and time when the shortened link expires.
                  suffix:
                    type: string
                    description: Generated suffix to access the shortened link.
        '400':
          description: Missing or invalid URL parameter in the request body.
        '500':
          description: Internal server error while creating the shortened link.
  '/{suffix}':
    get:
      summary: Redirect to original URL
      description: Redirects to the original URL corresponding to the provided suffix.
      parameters:
        - in: path
          name: suffix
          required: true
          schema:
            type: string
          description: Unique suffix associated with the shortened link.
      responses:
        '302':
          description: Temporary redirection to the original URL.
          headers:
            Location:
              schema:
                type: string
                format: uri
                description: Original URL corresponding to the suffix.
        '400':
          description: Invalid suffix provided in the request.
        '404':
          description: Shortened link not found for the provided suffix.
        '500':
          description: Internal server error while redirecting to the original URL.
